name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - name: Build
        env:
          VITE_BUSINESS_NAME: ${{ secrets.VITE_BUSINESS_NAME }}
          VITE_INSTAGRAM_HANDLE: ${{ secrets.VITE_INSTAGRAM_HANDLE }}
          VITE_INSTAGRAM_TOKEN: ${{ secrets.VITE_INSTAGRAM_TOKEN }}
          VITE_INSTAGRAM_USER_ID: ${{ secrets.VITE_INSTAGRAM_USER_ID }}
          VITE_CONTACT_EMAIL: ${{ secrets.VITE_CONTACT_EMAIL }}
          VITE_CONTACT_PHONE: ${{ secrets.VITE_CONTACT_PHONE }}
          VITE_BIO: ${{ secrets.VITE_BIO }}
          VITE_PORTFOLIO_URL: ${{ secrets.VITE_PORTFOLIO_URL }}
          VITE_DESIGNER_NAME: ${{ secrets.VITE_DESIGNER_NAME }}
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
